version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN_MAIN}
      - FLASK_PORT=8001
    ports:
      - "8001:8001"
    restart: unless-stopped