version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN_TESTING}
      - FLASK_PORT=8002
    ports:
      - "8002:8002"
    restart: unless-stopped