[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:flask_app]
command=gunicorn -w 4 -b 0.0.0.0:%(ENV_FLASK_PORT)s flask_app:app
directory=/app
environment=ENV="production"
stdout_logfile=/var/log/flask_app.log
stderr_logfile=/var/log/flask_app_err.log
autorestart=true

[program:bot]
command=python bot.py
directory=/app
stdout_logfile=/var/log/bot.log
stderr_logfile=/var/log/bot_err.log
autorestart=true