name: Build and Push Tagged Docker Image

on:
  push:
    branches: [main, testing]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image name and tag
        id: vars
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/racetalk-bot
          else
            IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/racetalk-bot-${GITHUB_REF_NAME}
          fi
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image with version tags
        run: |
          docker build -t $IMAGE_NAME:latest \
                       -t $IMAGE_NAME:$SHORT_SHA \
                       .

      - name: Push all tags
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$SHORT_SHA
